# Generated by Django 5.1.4 on 2026-06-14 10:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='variance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='budgetsheet',
            name='frozen_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='budgetsheet',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='unpaid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.CreateModel(
            name='BudgetChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('total_amount_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('Pending', '待审批'), ('Approved', '已通过'), ('Rejected', '已驳回')], default='Pending', max_length=16)),
                ('applicant_id', models.CharField(max_length=64)),
                ('approver_id', models.CharField(blank=True, default='', max_length=64)),
                ('approval_comment', models.TextField(blank=True, default='')),
                ('budget_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='budget_app.budgetsheet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetChangeRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='budget_app.budgetitem')),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_changes', to='budget_app.budgetchangerequest')),
            ],
            options={
                'unique_together': {('change_request', 'budget_item')},
            },
        ),
    ]
